-- Vehicle Management Module Schema
-- Please run this script in your Supabase SQL Editor

-- 1. vehicles table
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_no TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. vehicle_trips table
CREATE TABLE IF NOT EXISTS vehicle_trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE,
    from_city TEXT NOT NULL,
    to_city TEXT NOT NULL,
    departure_date DATE,
    arrival_date DATE,
    freight_income NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. vehicle_suppliers table
CREATE TABLE IF NOT EXISTS vehicle_suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    mobile TEXT,
    address TEXT,
    opening_balance NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. vehicle_expenses table
CREATE TABLE IF NOT EXISTS vehicle_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    amount NUMERIC DEFAULT 0,
    payment_type TEXT NOT NULL, -- 'Cash', 'Credit', 'Cash Supplier'
    supplier_id BIGINT REFERENCES vehicle_suppliers(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. vehicle_supplier_ledger table
CREATE TABLE IF NOT EXISTS vehicle_supplier_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT REFERENCES vehicle_suppliers(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    debit NUMERIC DEFAULT 0,
    credit NUMERIC DEFAULT 0,
    balance NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS and setup permissive policies for easy client access
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_supplier_ledger ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all on vehicles" ON vehicles;
CREATE POLICY "Allow all on vehicles" ON vehicles FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on vehicle_trips" ON vehicle_trips;
CREATE POLICY "Allow all on vehicle_trips" ON vehicle_trips FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on vehicle_suppliers" ON vehicle_suppliers;
CREATE POLICY "Allow all on vehicle_suppliers" ON vehicle_suppliers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on vehicle_expenses" ON vehicle_expenses;
CREATE POLICY "Allow all on vehicle_expenses" ON vehicle_expenses FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on vehicle_supplier_ledger" ON vehicle_supplier_ledger;
CREATE POLICY "Allow all on vehicle_supplier_ledger" ON vehicle_supplier_ledger FOR ALL USING (true) WITH CHECK (true);
